# kubectl apply -f service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  labels:
    app: sample-app-service
spec:
  selector:
    app: sample-app
  type: LoadBalancer # default, can be NodePort, LoadBalancer, ExternalName
  ports:
    - protocol: TCP
      port: 8081 # port of service
      targetPort: 8081 # port of application/pod
      nodePort: 30000  # NodePort you want to expose
    - protocol: TCP
      port: 8082 # port of service
      targetPort: 8082 # port of application/pod
      nodePort: 30001  # NodePort you want to expose